remote_theme: pages-themes/cayman@v0.2.0


title: System Design Primer - Samir Paul
description: Learn how to design large-scale systems. Prep for the system design interview. Includes Anki flashcards



excerpt_separator: ""   
author: Samir Paul

github:
  username: SamirPaul1             

twitter:
  username: SamirPaulb            
  card: summary_large_image

facebook:
  app_id: 6800281970014175
  publisher: 
  admins: 

google_site_verification: vJAOBxbJTCK2vXG-hLFeGsoC9hXgFlCpuJJ8AcJLROQ

webmaster_verifications:
  google: vJAOBxbJTCK2vXG-hLFeGsoC9hXgFlCpuJJ8AcJLROQ
  bing: 1A92FC2EC113F8616A21D76DA684A133
  yandex: fe6a06c57be84984
  pinterest: 24bac6e1fbf1750de40d59bb788d9dd9
  facebook: 3pkgruuk3kzlsn3jdfehgbd4sem1qb
  

social:
  # Change to your full name.
  # It will be displayed as the default author of the posts and the copyright owner in the Footer
  name: Samir Paul
  email:                   # change to your email address
  links: 
    # The first element serves as the copyright owner's link
    - https://twitter.com/SamirPaulb      # change to your twitter homepage
    - https://github.com/SamirPaul1       # change to your github homepage
    - https://www.linkedin.com/in/SamirPaul
    - https://www.facebook.com/SamirPaulb
    - https://www.instagram.com/SamirPaulb
  

# ↑ --------------------------
# The end of `jekyll-seo-tag` settings

google_analytics: 
  id: G-CP4QE6ZEV0


incremental: true


    
    
feed_items: 10
feed_update_period: daily
feed_update_frequency: 1


paginate: 5

pwa:
  enabled: true # Optional
  sw_src_filepath: service-worker.js # Optional
  sw_dest_filename: service-worker.js # Optional
  dest_js_directory: assets/js # Required
  precache_recent_posts_num: 5 # Optional
  precache_glob_directory: / # Optional
  precache_glob_patterns: # Optional
    - "{js,css,fonts}/**/*.{js,css,eot,svg,ttf,woff}"
    - index.html
  precache_glob_ignores: # Optional
    - sw-register.js
    - "fonts/**/*"




plugins:
- jekyll-seo-tag
- jekyll-remote-theme
- jekyll-feed
- jekyll-sitemap
- jekyll-target-blank
- jekyll-loading-lazy
- jekyll-include-cache
- jekyll-paginate
- jekyll-github-metadata
- jekyll-pwa-plugin
